### ISSUE TITLE
mp4/m4a/aac, ogg/opus & flac support, or maybe use ffmpeg/ffplay

### ISSUE THREAD

**Issue by SailorOnDaTea** [andreldm/kissplayer#22]
I figured it doesn't load mp4 audio files. So I couldn't load most of my archive.
Since mp4 is already popular and half of our music collection is already mp4 audio, I think it would be good to support more than mp3.
I personally don't use ogg vorbis but some guys prefer it. Recently realized my collection populated with m4a and flac format. These are like new standard today.
Since smartphones also support these formats, we only use mp3 because we already have some old songs or simply some of our devices can only play it(simple device like portable mp3 player, car stereo, boombox...)
Sometimes we have music videos in mp4 or mkv but most of them contain either mp3 or aac. video playback is not necessary but format support for audio would be nice.

**Comment by andreldm** [comment]
It's a limitation of FMOD Ex, which I have been trying to replace for something else(opensource) for quite a time. I'm not really attached to a file format, lots of mp3 and a few oggs here, but as many supported formats the better.

As there's much to do, a replacement for FMOD Ex seems to be the only reasonable way to "fix" this.
So, take a look at the issue #16, if you have any suggestion feel free to drop a comment there.
