### ISSUE TITLE
Create a new logo design

### ISSUE THREAD

**Issue by nunojesus** [andreldm/kissplayer#24]
Hi André,

I read your work and I download the player and it looks really good, but I think that it needs a new image, so if you want I can create a new logo and icon for the kissplayer.

greetings

**Comment by andreldm** [comment]
Hi there Nuno!
Thanks, I'm glad you like it :)
Yes, I would love if you craft a new logo, as you can see design is not something I'm good at, not even a bit.
Just to make it clear, lately I haven't been working on the project as much as I wanted, but it's not dead, whenever possible translations are updated, if bugs are reported I can gladly fix them or even add simple features.

With regards to the logo, I'm don't mean to tell what you are to do, just a couple of tips: keep the KISS principle in mind and if pick any color, it should contrast well with the dark gray interface.

Once again, thanks for you interest.

**Comment by nunojesus** [comment]
Hi see if you like this logos?

![kiss player](https://user-images.githubusercontent.com/34600369/39971169-d0c18d6a-56ee-11e8-8313-3492bd121cb4.png)

**Comment by andreldm** [comment]
Hi Nuno,
Great work, many thanks for working on those logos.
The 6th logo from top to bottom is the one that I like the most, just the colors are, ermm, too colorful, I don't, feels like something from the 80's =)
The sound wave is very nice, though if it could be a square it would be easier to use it as an icon.
I also really enjoyed the 'K' from the second from the last logo, but I think it's either one of the other situation.

**Comment by andreldm** [comment]
A propósito, se sentir mais confortável para trocar ideais em português fique a vontade ;)

**Comment by nunojesus** [comment]
Hi, I will change the 6th logo and made it a square, what colors do you like?

**Comment by nunojesus** [comment]
Hi  see if you like one of this colors and choose a font, I also create to icons to see how it looks the logo.

![kiss](https://user-images.githubusercontent.com/34600369/40060867-7675ea92-584f-11e8-8b51-82ac4b3e7816.png)

**Comment by andreldm** [comment]
Hello,
I picked the green one (and its font) and tried other colors on it:

![dark](https://user-images.githubusercontent.com/599565/40093453-b01267d2-5898-11e8-8e32-49596a2bfc54.png)

![white](https://user-images.githubusercontent.com/599565/40093458-b67695ee-5898-11e8-9c68-bc3e41ccfa7d.png)

The green looks good, but it's too Spotify-ish, I would like to avoid comparisons.
The gray seems boresome.
Finally the blue, I like it, maybe you can tweak the colors if you see fit.

What do you think?

**Comment by nunojesus** [comment]
Hi, the blue one is great, I will make the changes. What color do you want for the icon app background (the square and the circle)

**Comment by andreldm** [comment]
hmm, none? In that case the lines would need to be a little bolder to look good in the OS taskbar.

**Comment by nunojesus** [comment]
Ok I will do that.

**Comment by nunojesus** [comment]
Hello,

Here is the changes requested, so I create the logo, logotype with the text down the logo, 2 app buttons with no color in the background and with bold line and for last the logotype with the text in the right side of the logo the 1st one the thickness of the bars is the same as the thickness of the letters, which works very well, the 2nd the height of the letter is the same as the bars of the logo.

![kissplayer3](https://user-images.githubusercontent.com/34600369/40173690-90bb9f7e-59ca-11e8-85f2-ff9b6f288417.png)

**Comment by andreldm** [comment]
Many thanks Nuno, the new logo is awesome.
Do you happen to have it in svg format?

**Comment by nunojesus** [comment]
Not yet, but its easy to do that, i will send you later, can I make the pull request?

**Comment by andreldm** [comment]
Ahh, no need, it's easy to create vectors out of your last image.
I can't promise to include the logo this week, but as soon as I'm able, I'll make the due changes and give you credits for the logo in the About dialog :)

**Comment by nunojesus** [comment]
Im going to make the pull request now, with all the files.

**Comment by nunojesus** [comment]
Pull Request done!

Please see if everythig is ok.

Cheers!

**Comment by andreldm** [comment]
The latest release features the new logo.
Once again thank you very much!
